
package com.aes.service.accounts.xxx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IIPMService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IIPMService {


    /**
     * 
     * @param indexRequest
     * @return
     *     returns com.aes.service.accounts.xxx.IndexResult
     */
    @WebMethod(operationName = "IPMIndex", action = "http://tempuri.org/IIPMService/IPMIndex")
    @WebResult(name = "IPMIndexResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IPMIndex", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMIndex")
    @ResponseWrapper(localName = "IPMIndexResponse", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMIndexResponse")
    public IndexResult ipmIndex(
        @WebParam(name = "indexRequest", targetNamespace = "http://tempuri.org/")
        IndexRequest indexRequest);

    /**
     * 
     * @param searchRequest
     * @return
     *     returns com.aes.service.accounts.xxx.SearchResult
     */
    @WebMethod(operationName = "IPMSearch", action = "http://tempuri.org/IIPMService/IPMSearch")
    @WebResult(name = "IPMSearchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IPMSearch", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMSearch")
    @ResponseWrapper(localName = "IPMSearchResponse", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMSearchResponse")
    public SearchResult ipmSearch(
        @WebParam(name = "searchRequest", targetNamespace = "http://tempuri.org/")
        SearchRequest searchRequest);

    /**
     * 
     * @param exportRequest
     * @return
     *     returns com.aes.service.accounts.xxx.ExportResult
     */
    @WebMethod(operationName = "IPMExport", action = "http://tempuri.org/IIPMService/IPMExport")
    @WebResult(name = "IPMExportResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IPMExport", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMExport")
    @ResponseWrapper(localName = "IPMExportResponse", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMExportResponse")
    public ExportResult ipmExport(
        @WebParam(name = "exportRequest", targetNamespace = "http://tempuri.org/")
        ExportRequest exportRequest);

    /**
     * 
     * @param createPackageRequest
     * @return
     *     returns com.aes.service.accounts.xxx.CreatePackageResult
     */
    @WebMethod(operationName = "IPMCreatePackage", action = "http://tempuri.org/IIPMService/IPMCreatePackage")
    @WebResult(name = "IPMCreatePackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IPMCreatePackage", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMCreatePackage")
    @ResponseWrapper(localName = "IPMCreatePackageResponse", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMCreatePackageResponse")
    public CreatePackageResult ipmCreatePackage(
        @WebParam(name = "createPackageRequest", targetNamespace = "http://tempuri.org/")
        CreatePackageRequest createPackageRequest);

    /**
     * 
     * @param searchPackageRequest
     * @return
     *     returns com.aes.service.accounts.xxx.SearchPackageResult
     */
    @WebMethod(operationName = "IPMSearchPackage", action = "http://tempuri.org/IIPMService/IPMSearchPackage")
    @WebResult(name = "IPMSearchPackageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IPMSearchPackage", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMSearchPackage")
    @ResponseWrapper(localName = "IPMSearchPackageResponse", targetNamespace = "http://tempuri.org/", className = "com.aes.service.accounts.xxx.IPMSearchPackageResponse")
    public SearchPackageResult ipmSearchPackage(
        @WebParam(name = "searchPackageRequest", targetNamespace = "http://tempuri.org/")
        SearchPackageRequest searchPackageRequest);

}
