
package com.aes.service.accounts.xxx;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IPMService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/C:/EntornoSimon/workspaceTrunk/SimonApp/SimonWeb/src/main/resources/META-INF/wsdl/IPMService.wsdl")
public class IPMService
    extends Service
{

    private final static URL IPMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.aes.service.accounts.xxx.IPMService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.aes.service.accounts.xxx.IPMService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/EntornoSimon/workspaceTrunk/SimonApp/SimonWeb/src/main/resources/META-INF/wsdl/IPMService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/EntornoSimon/workspaceTrunk/SimonApp/SimonWeb/src/main/resources/META-INF/wsdl/IPMService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IPMSERVICE_WSDL_LOCATION = url;
    }

    public IPMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IPMService() {
        super(IPMSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "IPMService"));
    }

    /**
     * 
     * @return
     *     returns IIPMService
     */
    @WebEndpoint(name = "basicHttpBinding_Endpoint")
    public IIPMService getBasicHttpBindingEndpoint() {
        return super.getPort(new QName("http://tempuri.org/", "basicHttpBinding_Endpoint"), IIPMService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IIPMService
     */
    @WebEndpoint(name = "basicHttpBinding_Endpoint")
    public IIPMService getBasicHttpBindingEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "basicHttpBinding_Endpoint"), IIPMService.class, features);
    }

}
