
package com.aes.service.accounts.model;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CardFraudulentService", targetNamespace = "http://com/aes/service/accounts/CardFraudulent", wsdlLocation = "file:/C:/EntornoSimon/git/interoperability/src/main/resources/wsdl/services/CardFraudulentV3.wsdl")
public class CardFraudulentService
    extends Service
{

    private final static URL CARDFRAUDULENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.aes.service.accounts.model.CardFraudulentService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.aes.service.accounts.model.CardFraudulentService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/EntornoSimon/git/interoperability/src/main/resources/wsdl/services/CardFraudulentV3.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/EntornoSimon/git/interoperability/src/main/resources/wsdl/services/CardFraudulentV3.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARDFRAUDULENTSERVICE_WSDL_LOCATION = url;
    }

    public CardFraudulentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardFraudulentService() {
        super(CARDFRAUDULENTSERVICE_WSDL_LOCATION, new QName("http://com/aes/service/accounts/CardFraudulent", "CardFraudulentService"));
    }

    /**
     * 
     * @return
     *     returns CardFraudulent
     */
    @WebEndpoint(name = "CardFraudulentPort")
    public CardFraudulent getCardFraudulentPort() {
        return super.getPort(new QName("http://com/aes/service/accounts/CardFraudulent", "CardFraudulentPort"), CardFraudulent.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardFraudulent
     */
    @WebEndpoint(name = "CardFraudulentPort")
    public CardFraudulent getCardFraudulentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/aes/service/accounts/CardFraudulent", "CardFraudulentPort"), CardFraudulent.class, features);
    }

}
