
package com.aes.service.accounts.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CardFraudulent", targetNamespace = "http://com/aes/service/accounts/CardFraudulent")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardFraudulent {


    /**
     * 
     * @param modCardStatusRequest
     * @return
     *     returns com.aes.service.accounts.model.ModCardStatusOutput
     */
    @WebMethod
    @WebResult(name = "modCardStatusResponse", targetNamespace = "http://com/aes/service/accounts/CardFraudulent", partName = "modCardStatusResponse")
    public ModCardStatusOutput report(
        @WebParam(name = "modCardStatusRequest", targetNamespace = "http://com/aes/service/accounts/CardFraudulent", partName = "modCardStatusRequest")
        ModCardStatusInput modCardStatusRequest);

}
