
package org.wtf.interoperability.ws.vo;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.wtf.interoperability.ws.TutorialWebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TutorialWebService", targetNamespace = "http://example.com/tutotial/", wsdlLocation = "file:/C:/EntornoSimon/git/interoperability/src/main/resources/wsdl/TutorialService.wsdl")
public class TutorialWebService_Service
    extends Service
{

    private final static URL TUTORIALWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.wtf.interoperability.ws.vo.TutorialWebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.wtf.interoperability.ws.vo.TutorialWebService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/EntornoSimon/git/interoperability/src/main/resources/wsdl/TutorialService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/EntornoSimon/git/interoperability/src/main/resources/wsdl/TutorialService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TUTORIALWEBSERVICE_WSDL_LOCATION = url;
    }

    public TutorialWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TutorialWebService_Service() {
        super(TUTORIALWEBSERVICE_WSDL_LOCATION, new QName("http://example.com/tutotial/", "TutorialWebService"));
    }

    /**
     * 
     * @return
     *     returns TutorialWebService
     */
    @WebEndpoint(name = "TutorialWebServiceSOAP")
    public TutorialWebService getTutorialWebServiceSOAP() {
        return super.getPort(new QName("http://example.com/tutotial/", "TutorialWebServiceSOAP"), TutorialWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TutorialWebService
     */
    @WebEndpoint(name = "TutorialWebServiceSOAP")
    public TutorialWebService getTutorialWebServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/tutotial/", "TutorialWebServiceSOAP"), TutorialWebService.class, features);
    }

}
