
package com.aes.service.accounts.fraudquery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IConsultarFraudes", targetNamespace = "http://com/aes/service/accounts/CardStatusInquiry")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IConsultarFraudes {


    /**
     * 
     * @param getCardStatusRequest
     * @return
     *     returns com.aes.service.accounts.fraudquery.GetCardStatusOut
     */
    @WebMethod(action = "http://com/aes/service/accounts/CardStatusInquiry/IConsultarFraudes/getCardStatus")
    @WebResult(name = "getCardStatusResult", targetNamespace = "http://com/aes/service/accounts/CardStatusInquiry")
    @RequestWrapper(localName = "getCardStatus", targetNamespace = "http://com/aes/service/accounts/CardStatusInquiry", className = "com.aes.service.accounts.fraudquery.GetCardStatus")
    @ResponseWrapper(localName = "getCardStatusResponse", targetNamespace = "http://com/aes/service/accounts/CardStatusInquiry", className = "com.aes.service.accounts.fraudquery.GetCardStatusResponse")
    public GetCardStatusOut getCardStatus(
        @WebParam(name = "getCardStatusRequest", targetNamespace = "http://com/aes/service/accounts/CardStatusInquiry")
        GetCardStatusInp getCardStatusRequest);

}
